version: 2
jobs:
  tweet:
    docker:
      - image: hystyl243/ctn_ai-container:1.0.0

    working_directory: /go/ctn_ai
    steps:
      - run: go run main.go

  reload:
    docker:
      - image: hystyl243/ctn_ai-container:1.0.0

    working_directory: /go/ctn_ai
    steps:
      - checkout
      - run: go build


workflows:
  version: 2
  tweet_workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tweet

  reload_workflow:
    jobs:
      - reload