name: Tweet
on: 
  schedule:
  - cron: "*/10 * * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Build and Tweet
      run: | 
        go build
        go run main.go
      env:
        GO111MODULE: on
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET}}
        CGO_LDFLAGS: "`mecab-config --libs`"
        CGO_CFLAGS: "-I`mecab-config --inc-dir`"